name: ctr
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pip
  - python=3.10.13
  - pip:
    - black==24.1.1
    - category-encoders==2.6.3
    - deepctr-torch==0.2.9
    - flake8==7.0.0
    - isort==5.13.2
    - jupyter==1.0.0
    - openpyxl==3.0.10
    - catboost==1.2.2
    - hydra-core==1.3.0
    - holidays==0.24
    - lightgbm==3.3.2
    - matplotlib==3.5.3
    - seaborn==0.11.0
    - numpy==1.24.3
    - pandas==2.1.4
    - plotly==5.18.0
    - polars==0.19.19
    - prettytable==3.8.0
    - pyarrow==16.0.0
    - pytorch-tabnet==4.1.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - torch==1.13.0
    - torchaudio==0.13.0
    - torchvision==0.14.0
    - tqdm==4.65.0
    - xgboost==2.0.1
    - wandb==0.15.12
    - optuna==2.10.1