cat_features:
- site_id
- site_domain
- site_category
- app_id
- app_domain
- app_category
- device_id
- device_ip
- device_model
- device_model
- device_type
- device_conn_type
- banner_pos
- f_1
- f_2
- f_3
- f_4
- f_5
- f_6
- f_7
- f_8
- f_9
hash_features:
- site_id
- site_domain
- site_category
- app_id
- app_domain
- app_category
- device_id
- device_ip
- device_model
select_features:
- site_id
- site_domain
- site_category
- app_id
- app_domain
- app_category
- device_id
- device_ip
- device_model
- device_type
- device_conn_type
- banner_pos
- hour_of_day
- weekday
- f_1
- f_2
- f_3
- f_4
- f_5
- f_6
- f_7
- f_8
- f_9
