name: catboost

params:
  iterations: 10000
  task_type: CPU
  loss_function: Logloss
  eval_metric: AUC
  simple_ctr: Counter
  combinations_ctr: Counter
  max_ctr_complexity: 4
  learning_rate: 0.3
  od_type: Iter
  allow_writing_files: False

path: res/models/
results: 5fold-ctr-catboost
early_stopping_rounds: 100
seed: 42
verbose_eval: 100