name: catboost

params:
  iterations: 10000
  task_type: GPU
  loss_function: Logloss
  eval_metric: AUC
  simple_ctr: FeatureFreq
  combinations_ctr: FeatureFreq
  gpu_cat_features_storage: CpuPinnedMemory
  gpu_ram_part: 0.9
  max_ctr_complexity: 4
  learning_rate: 0.5
  od_type: Iter
  allow_writing_files: False

path: res/models/catboost/
results: 5fold-ctr-catboost
early_stopping_rounds: 100
seed: 42
verbose_eval: 100