name: deepfm

device: cuda
seed: 42
l2_reg_linear: 0.0001
l2_reg_embedding: 0.0001
dnn_activation: prelu
lr: 0.0001
dnn_dropout: 0.5
verbose: 1
patience: 2
mode: min
batch_size: 4096
epochs: 2

path: res/models/
preds: 5fold-ctr-lightgbm-0.4-seed414
results: 5fold-ctr-deepfm-0.4-seed42