name: lightgbm

params:
  boosting_type: gbdt
  objective: binary
  metric: auc
  learning_rate: 0.05
  bagging_seed: 602
  num_leaves: 200
  max_depth: -1
  min_child_weight: 0.03
  bagging_fraction: 0.4
  feature_fraction: 0.3
  lambda_l1: 0.4
  lambda_l2: 0.6
  verbose: -1
  n_jobs: -1

path: res/models/
results: 5fold-ctr-lightgbm-0.4-seed1119
early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100
seed: 42