name: lightgbm

params:
  boosting_type: gbdt
  objective: binary
  metric: auc
  learning_rate: 0.01
  num_leaves: 32
  max_depth: -1
  min_data_in_leaf: 100
  bagging_fraction: 0.8
  feature_fraction: 0.8
  lambda_l1: 0.001
  lambda_l2: 0.001
  seed: 42
  verbose: -1
  n_jobs: -1

path: res/models/
results: 5fold-ctr-lightgbm
early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100
seed: 42