name: lightgbm

params:
  boosting_type: gbdt
  objective: binary
  metric: auc
  learning_rate: 0.07
  bagging_seed: 11
  num_leaves: 491
  max_depth: -1
  min_child_weight: 0.03454472573214212
  bagging_fraction: 0.4181193142567742
  feature_fraction: 0.3797454081646243
  lambda_l1: 0.3899927210061127
  lambda_l2: 0.6485237330340494
  verbose: -1
  n_jobs: -1

path: res/models/
results: 5fold-ctr-lightgbm
early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100
seed: 42