name: wdl

device: cuda:0
seed: 42
l2_reg_linear: 0.0001
l2_reg_embedding: 0.0001
dnn_activation: prelu
lr: 0.0001
dnn_dropout: 0.5
verbose: 1
patience: 2
mode: min
batch_size: 4096
epochs: 5
gpus:
- 0
- 1
- 2
- 3

path: res/models/
results: 5fold-ctr-wdl-0.4-seed42