defaults:
  - _self_
  - data: dataset
  - generator: features
  - models: lightgbm
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  run:
    dir: .
  output_subdir: null

output:
  path: output
  submission: sample_submission
  name: rank-ensemble

preds:
- 5fold-ctr-lightgbm-0.3-seed42
- 5fold-ctr-lightgbm-0.4-seed42
- 5fold-ctr-lightgbm-0.4-seed414
- 5fold-ctr-lightgbm-0.4-seed602
- 5fold-ctr-lightgbm-0.4-seed1119
- 5fold-ctr-lightgbm-0.42-seed42
- 5fold-ctr-lightgbm-0.42-seed414