defaults:
  - _self_
  - data: dataset
  - generator: features
  - models: lightgbm
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  run:
    dir: .
  output_subdir: null

output:
  path: output
  submission: sample_submission
  name: rank-ensemble

preds:
- 5fold-ctr-lightgbm-65
- 5fold-ctr-lightgbm-8
- 5fold-ctr-lightgbm-hash
- 5fold-ctr-lightgbm-negative
- 5fold-ctr-lightgbm
