hydra:
  run:
    dir: .
  output_subdir: null

output:
  path: output
  submission: sample_submission
  name: 5fold-ctr-catboost

seed: 42

defaults:
  - _self_
  - data: dataset
  - generator: features
  - models: lightgbm
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled