hydra:
  run:
    dir: .
  output_subdir: null

output:
  path: output
  submission: sample_submission.csv
  name: 5fold-ctr-catboost.csv

sampling: 0.05

defaults:
  - _self_
  - data: dataset
  - models: lightgbm
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled